spring:
  h2:
    console:
      enabled: true
  jpa:
    generate-ddl: false
    show-sql: false
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:h2:mem:./inditexprecios
    username: sa
    password:
  flyway:
    enabled: true
    locations: classpath:/db/migration/H2
    schemas: inditexprecios
